apiVersion: helm.toolkit.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: weatherapp-ui
  namespace: apps
spec:
  chart:
    spec:
      version: ">=0.1.0"
  values:
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      hosts:
        - host: weatherapp.staging
          paths:
            - path: /
              pathType: ImplementationSpecific